name: "Check HACS"
on:
  pull_request:
    types: unlabeled

jobs:
    check:
        if: github.event.label.name == 'Not finished'
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Clone origin
              run: git clone --depth 1 https://github.com/hacs/default /tmp/default

            - name: Set category
              id: category
              run: echo "::set-output name=category::$(python3 -m scripts.changed.category)"

            - name: Set repository
              id: repository
              run: echo "::set-output name=repository::$(python3 -m scripts.changed.repository)"

            - name: HACS validation
              uses: "hacs/integration/action@master"
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              env:
                CHANGED_FILES: "${{ steps.category.outputs.category }}"
                REPOSITORY: "${{ steps.repository.outputs.repository }}"