name: Lint
on: [push, pull_request]

jobs:
  push:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Validate appdaemon
        run: jq --raw-output "." "appdaemon"

      - name: Validate blacklist
        run: jq --raw-output "." "blacklist"

      - name: Validate critical
        run: jq --raw-output "." "critical"

      - name: Validate integration
        run: jq --raw-output "." "integration"

      - name: Validate plugin
        run: jq --raw-output "." "plugin"

      - name: Validate python_script
        run: jq --raw-output "." "python_script"

      - name: Validate theme
        run: jq --raw-output "." "theme"